spring:
  application:
    name: ticket-service
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: ${SHOW_SQL:false}
  datasource:
    url: jdbc:h2:mem:bilet
    username: root
    password:
    driver-class-name: org.h2.Driver
